Hi team,

If you are confused as to why you are receiving this email or what [v31] means
it's likely because I have not written to this email list in over 8 months and
for a short period, I was writing on Substack.

Each time I sat down to write an update, it felt as though I was trying to
capture a cat outdoors: each effort to predict its direction only left me
leaping into the dirt as the animal darted away. Reflecting felt pointless, almost dangerous,
to look back, swivel my head, and reflect on each week as life bounded steadily
head. The longer the newsletter sat in my text editor, the more the pressure built
up. The longer I waited the bigger my expectations were for my takeaways and
reflections. To insinuate that this hiatus has been felt, let alone noticed, is
presumptious; however, this curated list holds value to me.

In information dense fashion, here are few highlights from the past months:

- graduated Middlebury College, writing a computer science thesis
- moved to san francisco
- led a group of 14y/o to Mumbai, India for a month-long peace education camp
- biked ~2,000 miles
- interned at Metaphor (https://metaphor.systems) for three months

Nicely laid out in a list, my life has appeared to progress in a linear and
simplistic fashion; however, half of these items came unexpected, with no
warning. Though unexpected, my life has been wholy great and I am excited
about the future.

My three month stint at Metaphor was filled with lots of learnings (from lots
of mistakes!), but at times I felt like I didn't have the time to think for
myself. Working at such an early stage is frantically swimming in open water.
Without bouys or lanes to guide you, you may not realize your left arm is
stronger and you've paddled at a 45deg angle from your target. The intensity and
urgency is an incredible learning opportunity and I am very grateful for the expereince.

Now, I am taking the leap to work for myself by contracting/consulting with
early stage startups. I am taking this shift to revisit my core values and build
conviction around what I want to spend my time doing.

In this effort, I am revitalizing my open reflection process to all of you. I
enjoyed the exercise of writing and working towards this email each week. It was
predictable and allowed me to fabricate a sense of output from activities that
are less measureable (reading, writing, thinking). I hope to use this as a way
to continue building that inherent sense of productivity in these actions that
are hard to measure.

I miss staying in-touch with all of you, so please don't hesitate to reply or
shoot me a text. Excited to talk with you all next week.

Have a great weekend,
Ben

Each week since I stopped writing
has brough a slew of reasons for pausing this process.
- my life felt like riding a bull and any effort to work
- a canoe paddling upstream
- an attempt to capture a cat outside, only hoping to predict its next movement
  only to be left diving in the dirt as it jumped in the other direction.

- so much has happened that it's left me paralyzed, searhing for some deep
  meaning.

- the longer this newletter waits, the more i have to write, the more I have had
  to learn and to summarize, the bigger reveal this has to be. like a volcanoe
  that hasn't erupted since the stone age only spitting a few globs of
  lava--dissapointing.

- however, I have now reached a trough, an aid-station a place where I can
  recooperate.

- I am focusing on realigning my values, doing things that fill my cup, and
  learning.


It has been over 8 months since I wrote on this newsletter. So much has happened
during that time that I have been overwhelmed each time I have sat down to write
or think about writing to all of you. 



I am taking a leap to work for myself. It's almost a values detox where it's
easy to feel like you're moving in the right direction if your going so fast.
Imagine swimming with your head in the water, paddling as fast as you can,
without looking up you might not notice your right arm is stronger and you've
paddled at a 45 deg angle from where you took off.

Taking a breath helps us reframe. Do I want to do science? Do I want to design?
What about graduate school?

In my past experiences, it's been hard to think about these larger questions in
the moments while cleaning the dishes or tidying your room. You practically get
nowhere, unable to test your thoughts or actions. You continue to think in
hypotheticals as you make dinner, but you have little idea.


I'll cover some high-level happenings in my life

* Some noticeable changes

- Switched my text editors
- Took a hiatus from coding
- Went to india
- Planning to do contract work
- moved to san fran
- graduated college summa cum laude
- wrote my thesis

* Exciting new things
- being around startups and friends
- superconductors
- ai
- search

* Goals
- work for a company as a founding engineer
- build cool things
- setup more regular interesting conversations
- dev meetups
- working with friends
- building cool shit (again)

* Ideas
